var fs=require('fs'),D='c:/Users/Coco/Documents/GitHub/arcMenuOnKde/';
var Q=String.fromCharCode(34);
var h=fs.readFileSync(D+'_hdr.txt','utf8').split('@').join(Q).split('\n');
var b=fs.readFileSync(D+'_body.txt','utf8').split('@').join(Q).split('\n');
var p=D+'plasma-arcmenu/package/contents/ui/config/ConfigMenu.qml';
var s=fs.readFileSync(p,'utf8');
var NL=s.indexOf('\r\n')>=0?'\r\n':'\n';
var L=s.split(/\r?\n/);
if(L[164].indexOf('function cfgName')<0)throw new Error('anchor1');
if(L[211].indexOf('Timer {')<0)throw new Error('anchor2');
if(L[12].indexOf('Plasma Apply only reads')<0)throw new Error('anchor3');
var ob=b.indexOf('    function openSubPage(component, title) {');b.splice(ob,0,'');
L.splice(164,57,...b);
L.splice(12,7,...h);
fs.writeFileSync(p,L.join(NL),'utf8');
console.log('done lines',L.length);