.pragma library

/** Bundled ArcMenu panel-button presets (contents/icons/menu-button/). */

var PRESET_ICON_IDS = [
    "distro-arch",
    "distro-arch-symbolic",
    "distro-athena",
    "distro-budgie-symbolic",
    "distro-cachyos",
    "distro-cachyos-symbolic",
    "distro-centos",
    "distro-centos-symbolic",
    "distro-debian",
    "distro-debian-symbolic",
    "distro-endeavouros",
    "distro-endeavouros-alt-symbolic",
    "distro-endeavouros-symbolic",
    "distro-fedora",
    "distro-fedora-symbolic",
    "distro-gentoo",
    "distro-gentoo-symbolic",
    "distro-gnome-symbolic",
    "distro-kali-linux",
    "distro-kali-linux-symbolic",
    "distro-manjaro",
    "distro-manjaro-symbolic",
    "distro-mx-symbolic",
    "distro-nixos",
    "distro-nixos-symbolic",
    "distro-nobara-symbolic",
    "distro-opensuse",
    "distro-opensuse-alt",
    "distro-opensuse-alt-symbolic",
    "distro-opensuse-symbolic",
    "distro-oreon-symbolic",
    "distro-pardus-symbolic",
    "distro-pop-os",
    "distro-pop-os-symbolic",
    "distro-pureos-symbolic",
    "distro-raspbian",
    "distro-raspbian-symbolic",
    "distro-redhat",
    "distro-redhat-symbolic",
    "distro-solus",
    "distro-solus-symbolic",
    "distro-ubuntu",
    "distro-ubuntu-symbolic",
    "distro-voyager-symbolic",
    "distro-zorin",
    "distro-zorin-symbolic",
    "icon-3d-symbolic",
    "icon-alien-symbolic",
    "icon-app-launcher-symbolic",
    "icon-apps-symbolic",
    "icon-arcmenu-logo-alt-symbolic",
    "icon-arcmenu-logo-symbolic",
    "icon-arcmenu-old-alt-symbolic",
    "icon-arcmenu-oldest-symbolic",
    "icon-arcmenu-old-symbolic",
    "icon-arrow-symbolic",
    "icon-a-symbolic",
    "icon-bat-symbolic",
    "icon-bug-symbolic",
    "icon-cita-symbolic",
    "icon-cloud-symbolic",
    "icon-curved-a-symbolic",
    "icon-diamond-square-symbolic",
    "icon-dimond-win-symbolic",
    "icon-dolphin-symbolic",
    "icon-dota-symbolic",
    "icon-dragonheart-symbolic",
    "icon-dragon-symbolic",
    "icon-dra-symbolic",
    "icon-eclipse-symbolic",
    "icon-equal-symbolic",
    "icon-fly-symbolic",
    "icon-focus-symbolic",
    "icon-football2-symbolic",
    "icon-football-symbolic",
    "icon-gnacs-symbolic",
    "icon-groove-symbolic",
    "icon-heddy-symbolic",
    "icon-helmet-symbolic",
    "icon-hexagon-symbolic",
    "icon-kaaet-symbolic",
    "icon-launcher-symbolic",
    "icon-lins-symbolic",
    "icon-loveheart-symbolic",
    "icon-octo-maze-symbolic",
    "icon-pacman-symbolic",
    "icon-pac-symbolic",
    "icon-paint-palette-symbolic",
    "icon-peaks-symbolic",
    "icon-peeks-symbolic",
    "icon-pie-symbolic",
    "icon-pointer-symbolic",
    "icon-pyrimid-symbolic",
    "icon-record-symbolic",
    "icon-rewind-symbolic",
    "icon-robots-symbolic",
    "icon-round-symbolic",
    "icon-saucer-symbolic",
    "icon-search-glass-symbolic",
    "icon-sheild-symbolic",
    "icon-snap-symbolic",
    "icon-somnia-symbolic",
    "icon-start-box-symbolic",
    "icon-step-symbolic",
    "icon-sums-symbolic",
    "icon-swirl-symbolic",
    "icon-time-symbolic",
    "icon-toxic2-symbolic",
    "icon-toxic-symbolic",
    "icon-transform-symbolic",
    "icon-tree-symbolic",
    "icon-triple-dash-symbolic",
    "icon-utool-symbolic",
    "icon-vancer-symbolic",
    "icon-vibe-symbolic",
    "icon-whirl-circle-symbolic",
    "icon-whirl-symbolic",
    "icon-zegon-symbolic",
];

function allIds() {
    return PRESET_ICON_IDS.slice();
}

function isPreset(id) {
    if (!id) return false;
    return PRESET_ICON_IDS.indexOf(String(id)) >= 0;
}

function groupOf(id) {
    var s = String(id || "");
    if (s.indexOf("distro-") === 0) return "distro";
    if (isPreset(s)) return "extension";
    return "system";
}

function isSymbolic(id) {
    return String(id || "").indexOf("-symbolic") >= 0;
}
